spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/grave-manager-db
    username: postgres
    password: password

jwt:
  permit:
    all:
      - /swagger-ui/**
      - /swagger-resources/*
      - /v3/api-docs/**
      - /v1/**